//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace CarProject.sms_ws {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SmsPanelWebserviceBinding", Namespace="urn:sms_webservice_wsdl")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(array_tree))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(array_receive))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(array_number_state))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(array_number))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(array_cat_list))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(array_number_in_cat))]
    public partial class SmsPanelWebservice : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback sms_get_number_in_catOperationCompleted;
        
        private System.Threading.SendOrPostCallback sms_get_cat_listOperationCompleted;
        
        private System.Threading.SendOrPostCallback send_smsOperationCompleted;
        
        private System.Threading.SendOrPostCallback get_numberOperationCompleted;
        
        private System.Threading.SendOrPostCallback sms_deliverOperationCompleted;
        
        private System.Threading.SendOrPostCallback is_number_in_blacklistOperationCompleted;
        
        private System.Threading.SendOrPostCallback add_userOperationCompleted;
        
        private System.Threading.SendOrPostCallback sms_user_infoOperationCompleted;
        
        private System.Threading.SendOrPostCallback sms_creditOperationCompleted;
        
        private System.Threading.SendOrPostCallback sms_add_numberOperationCompleted;
        
        private System.Threading.SendOrPostCallback sms_receiveOperationCompleted;
        
        private System.Threading.SendOrPostCallback sms_receive_change_readOperationCompleted;
        
        private System.Threading.SendOrPostCallback sms_count_bulk_genderOperationCompleted;
        
        private System.Threading.SendOrPostCallback sms_send_bulk_genderOperationCompleted;
        
        private System.Threading.SendOrPostCallback sms_count_bank_genderOperationCompleted;
        
        private System.Threading.SendOrPostCallback user_add_catOperationCompleted;
        
        private System.Threading.SendOrPostCallback convert_unixtime_to_jalaliOperationCompleted;
        
        private System.Threading.SendOrPostCallback number_queryOperationCompleted;
        
        private System.Threading.SendOrPostCallback convert_jalali_to_unixtimestampOperationCompleted;
        
        private System.Threading.SendOrPostCallback admin_allow_number_newOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SmsPanelWebservice() {
            this.Url = global::CarProject.Properties.Settings.Default.CarProject_sms_ws_SmsPanelWebservice;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event sms_get_number_in_catCompletedEventHandler sms_get_number_in_catCompleted;
        
        /// <remarks/>
        public event sms_get_cat_listCompletedEventHandler sms_get_cat_listCompleted;
        
        /// <remarks/>
        public event send_smsCompletedEventHandler send_smsCompleted;
        
        /// <remarks/>
        public event get_numberCompletedEventHandler get_numberCompleted;
        
        /// <remarks/>
        public event sms_deliverCompletedEventHandler sms_deliverCompleted;
        
        /// <remarks/>
        public event is_number_in_blacklistCompletedEventHandler is_number_in_blacklistCompleted;
        
        /// <remarks/>
        public event add_userCompletedEventHandler add_userCompleted;
        
        /// <remarks/>
        public event sms_user_infoCompletedEventHandler sms_user_infoCompleted;
        
        /// <remarks/>
        public event sms_creditCompletedEventHandler sms_creditCompleted;
        
        /// <remarks/>
        public event sms_add_numberCompletedEventHandler sms_add_numberCompleted;
        
        /// <remarks/>
        public event sms_receiveCompletedEventHandler sms_receiveCompleted;
        
        /// <remarks/>
        public event sms_receive_change_readCompletedEventHandler sms_receive_change_readCompleted;
        
        /// <remarks/>
        public event sms_count_bulk_genderCompletedEventHandler sms_count_bulk_genderCompleted;
        
        /// <remarks/>
        public event sms_send_bulk_genderCompletedEventHandler sms_send_bulk_genderCompleted;
        
        /// <remarks/>
        public event sms_count_bank_genderCompletedEventHandler sms_count_bank_genderCompleted;
        
        /// <remarks/>
        public event user_add_catCompletedEventHandler user_add_catCompleted;
        
        /// <remarks/>
        public event convert_unixtime_to_jalaliCompletedEventHandler convert_unixtime_to_jalaliCompleted;
        
        /// <remarks/>
        public event number_queryCompletedEventHandler number_queryCompleted;
        
        /// <remarks/>
        public event convert_jalali_to_unixtimestampCompletedEventHandler convert_jalali_to_unixtimestampCompleted;
        
        /// <remarks/>
        public event admin_allow_number_newCompletedEventHandler admin_allow_number_newCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("sms_webservice_wsdl#sms_get_number_in_cat", RequestNamespace="sms_webservice_wsdl", ResponseNamespace="sms_webservice_wsdl")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public array_number_in_cat[] sms_get_number_in_cat(string username, string password, int catid, int start, int perpage, string order) {
            object[] results = this.Invoke("sms_get_number_in_cat", new object[] {
                        username,
                        password,
                        catid,
                        start,
                        perpage,
                        order});
            return ((array_number_in_cat[])(results[0]));
        }
        
        /// <remarks/>
        public void sms_get_number_in_catAsync(string username, string password, int catid, int start, int perpage, string order) {
            this.sms_get_number_in_catAsync(username, password, catid, start, perpage, order, null);
        }
        
        /// <remarks/>
        public void sms_get_number_in_catAsync(string username, string password, int catid, int start, int perpage, string order, object userState) {
            if ((this.sms_get_number_in_catOperationCompleted == null)) {
                this.sms_get_number_in_catOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsms_get_number_in_catOperationCompleted);
            }
            this.InvokeAsync("sms_get_number_in_cat", new object[] {
                        username,
                        password,
                        catid,
                        start,
                        perpage,
                        order}, this.sms_get_number_in_catOperationCompleted, userState);
        }
        
        private void Onsms_get_number_in_catOperationCompleted(object arg) {
            if ((this.sms_get_number_in_catCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sms_get_number_in_catCompleted(this, new sms_get_number_in_catCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("sms_webservice_wsdl#sms_get_cat_list", RequestNamespace="sms_webservice_wsdl", ResponseNamespace="sms_webservice_wsdl")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public array_cat_list[] sms_get_cat_list(string username, string password) {
            object[] results = this.Invoke("sms_get_cat_list", new object[] {
                        username,
                        password});
            return ((array_cat_list[])(results[0]));
        }
        
        /// <remarks/>
        public void sms_get_cat_listAsync(string username, string password) {
            this.sms_get_cat_listAsync(username, password, null);
        }
        
        /// <remarks/>
        public void sms_get_cat_listAsync(string username, string password, object userState) {
            if ((this.sms_get_cat_listOperationCompleted == null)) {
                this.sms_get_cat_listOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsms_get_cat_listOperationCompleted);
            }
            this.InvokeAsync("sms_get_cat_list", new object[] {
                        username,
                        password}, this.sms_get_cat_listOperationCompleted, userState);
        }
        
        private void Onsms_get_cat_listOperationCompleted(object arg) {
            if ((this.sms_get_cat_listCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sms_get_cat_listCompleted(this, new sms_get_cat_listCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("sms_webservice_wsdl#send_sms", RequestNamespace="sms_webservice_wsdl", ResponseNamespace="sms_webservice_wsdl")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string[] send_sms(string username, string password, string[] sender_number, string[] receiver_number, string[] note, string[] date, string[] request_uniqueid, string[] flash, string onlysend) {
            object[] results = this.Invoke("send_sms", new object[] {
                        username,
                        password,
                        sender_number,
                        receiver_number,
                        note,
                        date,
                        request_uniqueid,
                        flash,
                        onlysend});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void send_smsAsync(string username, string password, string[] sender_number, string[] receiver_number, string[] note, string[] date, string[] request_uniqueid, string[] flash, string onlysend) {
            this.send_smsAsync(username, password, sender_number, receiver_number, note, date, request_uniqueid, flash, onlysend, null);
        }
        
        /// <remarks/>
        public void send_smsAsync(string username, string password, string[] sender_number, string[] receiver_number, string[] note, string[] date, string[] request_uniqueid, string[] flash, string onlysend, object userState) {
            if ((this.send_smsOperationCompleted == null)) {
                this.send_smsOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsend_smsOperationCompleted);
            }
            this.InvokeAsync("send_sms", new object[] {
                        username,
                        password,
                        sender_number,
                        receiver_number,
                        note,
                        date,
                        request_uniqueid,
                        flash,
                        onlysend}, this.send_smsOperationCompleted, userState);
        }
        
        private void Onsend_smsOperationCompleted(object arg) {
            if ((this.send_smsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.send_smsCompleted(this, new send_smsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("sms_webservice_wsdl#get_number", RequestNamespace="sms_webservice_wsdl", ResponseNamespace="sms_webservice_wsdl")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public array_number[] get_number(string username, string password) {
            object[] results = this.Invoke("get_number", new object[] {
                        username,
                        password});
            return ((array_number[])(results[0]));
        }
        
        /// <remarks/>
        public void get_numberAsync(string username, string password) {
            this.get_numberAsync(username, password, null);
        }
        
        /// <remarks/>
        public void get_numberAsync(string username, string password, object userState) {
            if ((this.get_numberOperationCompleted == null)) {
                this.get_numberOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_numberOperationCompleted);
            }
            this.InvokeAsync("get_number", new object[] {
                        username,
                        password}, this.get_numberOperationCompleted, userState);
        }
        
        private void Onget_numberOperationCompleted(object arg) {
            if ((this.get_numberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_numberCompleted(this, new get_numberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("sms_webservice_wsdl#sms_deliver", RequestNamespace="sms_webservice_wsdl", ResponseNamespace="sms_webservice_wsdl")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public long[] sms_deliver(string[] smsid_arr, int dargah) {
            object[] results = this.Invoke("sms_deliver", new object[] {
                        smsid_arr,
                        dargah});
            return ((long[])(results[0]));
        }
        
        /// <remarks/>
        public void sms_deliverAsync(string[] smsid_arr, int dargah) {
            this.sms_deliverAsync(smsid_arr, dargah, null);
        }
        
        /// <remarks/>
        public void sms_deliverAsync(string[] smsid_arr, int dargah, object userState) {
            if ((this.sms_deliverOperationCompleted == null)) {
                this.sms_deliverOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsms_deliverOperationCompleted);
            }
            this.InvokeAsync("sms_deliver", new object[] {
                        smsid_arr,
                        dargah}, this.sms_deliverOperationCompleted, userState);
        }
        
        private void Onsms_deliverOperationCompleted(object arg) {
            if ((this.sms_deliverCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sms_deliverCompleted(this, new sms_deliverCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("sms_webservice_wsdl#is_number_in_blacklist", RequestNamespace="sms_webservice_wsdl", ResponseNamespace="sms_webservice_wsdl")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public array_number_state[] is_number_in_blacklist(string[] number) {
            object[] results = this.Invoke("is_number_in_blacklist", new object[] {
                        number});
            return ((array_number_state[])(results[0]));
        }
        
        /// <remarks/>
        public void is_number_in_blacklistAsync(string[] number) {
            this.is_number_in_blacklistAsync(number, null);
        }
        
        /// <remarks/>
        public void is_number_in_blacklistAsync(string[] number, object userState) {
            if ((this.is_number_in_blacklistOperationCompleted == null)) {
                this.is_number_in_blacklistOperationCompleted = new System.Threading.SendOrPostCallback(this.Onis_number_in_blacklistOperationCompleted);
            }
            this.InvokeAsync("is_number_in_blacklist", new object[] {
                        number}, this.is_number_in_blacklistOperationCompleted, userState);
        }
        
        private void Onis_number_in_blacklistOperationCompleted(object arg) {
            if ((this.is_number_in_blacklistCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.is_number_in_blacklistCompleted(this, new is_number_in_blacklistCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("sms_webservice_wsdl#add_user", RequestNamespace="sms_webservice_wsdl", ResponseNamespace="sms_webservice_wsdl")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string add_user(string admin_username, string admin_password, string username, string password, string email, string fullname, string mobile, int catid) {
            object[] results = this.Invoke("add_user", new object[] {
                        admin_username,
                        admin_password,
                        username,
                        password,
                        email,
                        fullname,
                        mobile,
                        catid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void add_userAsync(string admin_username, string admin_password, string username, string password, string email, string fullname, string mobile, int catid) {
            this.add_userAsync(admin_username, admin_password, username, password, email, fullname, mobile, catid, null);
        }
        
        /// <remarks/>
        public void add_userAsync(string admin_username, string admin_password, string username, string password, string email, string fullname, string mobile, int catid, object userState) {
            if ((this.add_userOperationCompleted == null)) {
                this.add_userOperationCompleted = new System.Threading.SendOrPostCallback(this.Onadd_userOperationCompleted);
            }
            this.InvokeAsync("add_user", new object[] {
                        admin_username,
                        admin_password,
                        username,
                        password,
                        email,
                        fullname,
                        mobile,
                        catid}, this.add_userOperationCompleted, userState);
        }
        
        private void Onadd_userOperationCompleted(object arg) {
            if ((this.add_userCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.add_userCompleted(this, new add_userCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("sms_webservice_wsdl#sms_user_info", RequestNamespace="sms_webservice_wsdl", ResponseNamespace="sms_webservice_wsdl")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public return_array_user_info sms_user_info(string username, string password) {
            object[] results = this.Invoke("sms_user_info", new object[] {
                        username,
                        password});
            return ((return_array_user_info)(results[0]));
        }
        
        /// <remarks/>
        public void sms_user_infoAsync(string username, string password) {
            this.sms_user_infoAsync(username, password, null);
        }
        
        /// <remarks/>
        public void sms_user_infoAsync(string username, string password, object userState) {
            if ((this.sms_user_infoOperationCompleted == null)) {
                this.sms_user_infoOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsms_user_infoOperationCompleted);
            }
            this.InvokeAsync("sms_user_info", new object[] {
                        username,
                        password}, this.sms_user_infoOperationCompleted, userState);
        }
        
        private void Onsms_user_infoOperationCompleted(object arg) {
            if ((this.sms_user_infoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sms_user_infoCompleted(this, new sms_user_infoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("sms_webservice_wsdl#sms_credit", RequestNamespace="sms_webservice_wsdl", ResponseNamespace="sms_webservice_wsdl")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public int sms_credit(string username, string password) {
            object[] results = this.Invoke("sms_credit", new object[] {
                        username,
                        password});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void sms_creditAsync(string username, string password) {
            this.sms_creditAsync(username, password, null);
        }
        
        /// <remarks/>
        public void sms_creditAsync(string username, string password, object userState) {
            if ((this.sms_creditOperationCompleted == null)) {
                this.sms_creditOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsms_creditOperationCompleted);
            }
            this.InvokeAsync("sms_credit", new object[] {
                        username,
                        password}, this.sms_creditOperationCompleted, userState);
        }
        
        private void Onsms_creditOperationCompleted(object arg) {
            if ((this.sms_creditCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sms_creditCompleted(this, new sms_creditCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("sms_webservice_wsdl#sms_add_number", RequestNamespace="sms_webservice_wsdl", ResponseNamespace="sms_webservice_wsdl")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string sms_add_number(string username, string password, string fullname, string number, int catid, string gender, string fullname_en, string gender_en) {
            object[] results = this.Invoke("sms_add_number", new object[] {
                        username,
                        password,
                        fullname,
                        number,
                        catid,
                        gender,
                        fullname_en,
                        gender_en});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void sms_add_numberAsync(string username, string password, string fullname, string number, int catid, string gender, string fullname_en, string gender_en) {
            this.sms_add_numberAsync(username, password, fullname, number, catid, gender, fullname_en, gender_en, null);
        }
        
        /// <remarks/>
        public void sms_add_numberAsync(string username, string password, string fullname, string number, int catid, string gender, string fullname_en, string gender_en, object userState) {
            if ((this.sms_add_numberOperationCompleted == null)) {
                this.sms_add_numberOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsms_add_numberOperationCompleted);
            }
            this.InvokeAsync("sms_add_number", new object[] {
                        username,
                        password,
                        fullname,
                        number,
                        catid,
                        gender,
                        fullname_en,
                        gender_en}, this.sms_add_numberOperationCompleted, userState);
        }
        
        private void Onsms_add_numberOperationCompleted(object arg) {
            if ((this.sms_add_numberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sms_add_numberCompleted(this, new sms_add_numberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("sms_webservice_wsdl#sms_receive", RequestNamespace="sms_webservice_wsdl", ResponseNamespace="sms_webservice_wsdl")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public array_receive[] sms_receive(string username, string password, string number, int catid, int start, int perpage, int read, string order) {
            object[] results = this.Invoke("sms_receive", new object[] {
                        username,
                        password,
                        number,
                        catid,
                        start,
                        perpage,
                        read,
                        order});
            return ((array_receive[])(results[0]));
        }
        
        /// <remarks/>
        public void sms_receiveAsync(string username, string password, string number, int catid, int start, int perpage, int read, string order) {
            this.sms_receiveAsync(username, password, number, catid, start, perpage, read, order, null);
        }
        
        /// <remarks/>
        public void sms_receiveAsync(string username, string password, string number, int catid, int start, int perpage, int read, string order, object userState) {
            if ((this.sms_receiveOperationCompleted == null)) {
                this.sms_receiveOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsms_receiveOperationCompleted);
            }
            this.InvokeAsync("sms_receive", new object[] {
                        username,
                        password,
                        number,
                        catid,
                        start,
                        perpage,
                        read,
                        order}, this.sms_receiveOperationCompleted, userState);
        }
        
        private void Onsms_receiveOperationCompleted(object arg) {
            if ((this.sms_receiveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sms_receiveCompleted(this, new sms_receiveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("sms_webservice_wsdl#sms_receive_change_read", RequestNamespace="sms_webservice_wsdl", ResponseNamespace="sms_webservice_wsdl")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string sms_receive_change_read(string username, string password, long[] id, int read) {
            object[] results = this.Invoke("sms_receive_change_read", new object[] {
                        username,
                        password,
                        id,
                        read});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void sms_receive_change_readAsync(string username, string password, long[] id, int read) {
            this.sms_receive_change_readAsync(username, password, id, read, null);
        }
        
        /// <remarks/>
        public void sms_receive_change_readAsync(string username, string password, long[] id, int read, object userState) {
            if ((this.sms_receive_change_readOperationCompleted == null)) {
                this.sms_receive_change_readOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsms_receive_change_readOperationCompleted);
            }
            this.InvokeAsync("sms_receive_change_read", new object[] {
                        username,
                        password,
                        id,
                        read}, this.sms_receive_change_readOperationCompleted, userState);
        }
        
        private void Onsms_receive_change_readOperationCompleted(object arg) {
            if ((this.sms_receive_change_readCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sms_receive_change_readCompleted(this, new sms_receive_change_readCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("sms_webservice_wsdl#sms_count_bulk_gender", RequestNamespace="sms_webservice_wsdl", ResponseNamespace="sms_webservice_wsdl")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string sms_count_bulk_gender(string bankid, int gender, string receiver_number_kind, int age_start, int age_end, int receiver_number_perfix, int dargah) {
            object[] results = this.Invoke("sms_count_bulk_gender", new object[] {
                        bankid,
                        gender,
                        receiver_number_kind,
                        age_start,
                        age_end,
                        receiver_number_perfix,
                        dargah});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void sms_count_bulk_genderAsync(string bankid, int gender, string receiver_number_kind, int age_start, int age_end, int receiver_number_perfix, int dargah) {
            this.sms_count_bulk_genderAsync(bankid, gender, receiver_number_kind, age_start, age_end, receiver_number_perfix, dargah, null);
        }
        
        /// <remarks/>
        public void sms_count_bulk_genderAsync(string bankid, int gender, string receiver_number_kind, int age_start, int age_end, int receiver_number_perfix, int dargah, object userState) {
            if ((this.sms_count_bulk_genderOperationCompleted == null)) {
                this.sms_count_bulk_genderOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsms_count_bulk_genderOperationCompleted);
            }
            this.InvokeAsync("sms_count_bulk_gender", new object[] {
                        bankid,
                        gender,
                        receiver_number_kind,
                        age_start,
                        age_end,
                        receiver_number_perfix,
                        dargah}, this.sms_count_bulk_genderOperationCompleted, userState);
        }
        
        private void Onsms_count_bulk_genderOperationCompleted(object arg) {
            if ((this.sms_count_bulk_genderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sms_count_bulk_genderCompleted(this, new sms_count_bulk_genderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("sms_webservice_wsdl#sms_send_bulk_gender", RequestNamespace="sms_webservice_wsdl", ResponseNamespace="sms_webservice_wsdl")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string sms_send_bulk_gender(
                    string username, 
                    string password, 
                    string sender_number, 
                    string bankid, 
                    string note, 
                    int date, 
                    int record_start, 
                    int receiver_count, 
                    int gender, 
                    string receiver_number_kind, 
                    int age_start, 
                    int age_end, 
                    int receiver_number_perfix, 
                    string billing_title, 
                    string request_uniqueid, 
                    int dargah) {
            object[] results = this.Invoke("sms_send_bulk_gender", new object[] {
                        username,
                        password,
                        sender_number,
                        bankid,
                        note,
                        date,
                        record_start,
                        receiver_count,
                        gender,
                        receiver_number_kind,
                        age_start,
                        age_end,
                        receiver_number_perfix,
                        billing_title,
                        request_uniqueid,
                        dargah});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void sms_send_bulk_genderAsync(
                    string username, 
                    string password, 
                    string sender_number, 
                    string bankid, 
                    string note, 
                    int date, 
                    int record_start, 
                    int receiver_count, 
                    int gender, 
                    string receiver_number_kind, 
                    int age_start, 
                    int age_end, 
                    int receiver_number_perfix, 
                    string billing_title, 
                    string request_uniqueid, 
                    int dargah) {
            this.sms_send_bulk_genderAsync(username, password, sender_number, bankid, note, date, record_start, receiver_count, gender, receiver_number_kind, age_start, age_end, receiver_number_perfix, billing_title, request_uniqueid, dargah, null);
        }
        
        /// <remarks/>
        public void sms_send_bulk_genderAsync(
                    string username, 
                    string password, 
                    string sender_number, 
                    string bankid, 
                    string note, 
                    int date, 
                    int record_start, 
                    int receiver_count, 
                    int gender, 
                    string receiver_number_kind, 
                    int age_start, 
                    int age_end, 
                    int receiver_number_perfix, 
                    string billing_title, 
                    string request_uniqueid, 
                    int dargah, 
                    object userState) {
            if ((this.sms_send_bulk_genderOperationCompleted == null)) {
                this.sms_send_bulk_genderOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsms_send_bulk_genderOperationCompleted);
            }
            this.InvokeAsync("sms_send_bulk_gender", new object[] {
                        username,
                        password,
                        sender_number,
                        bankid,
                        note,
                        date,
                        record_start,
                        receiver_count,
                        gender,
                        receiver_number_kind,
                        age_start,
                        age_end,
                        receiver_number_perfix,
                        billing_title,
                        request_uniqueid,
                        dargah}, this.sms_send_bulk_genderOperationCompleted, userState);
        }
        
        private void Onsms_send_bulk_genderOperationCompleted(object arg) {
            if ((this.sms_send_bulk_genderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sms_send_bulk_genderCompleted(this, new sms_send_bulk_genderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("sms_webservice_wsdl#sms_count_bank_gender", RequestNamespace="sms_webservice_wsdl", ResponseNamespace="sms_webservice_wsdl")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public array_tree[] sms_count_bank_gender(int parentid, int dargah) {
            object[] results = this.Invoke("sms_count_bank_gender", new object[] {
                        parentid,
                        dargah});
            return ((array_tree[])(results[0]));
        }
        
        /// <remarks/>
        public void sms_count_bank_genderAsync(int parentid, int dargah) {
            this.sms_count_bank_genderAsync(parentid, dargah, null);
        }
        
        /// <remarks/>
        public void sms_count_bank_genderAsync(int parentid, int dargah, object userState) {
            if ((this.sms_count_bank_genderOperationCompleted == null)) {
                this.sms_count_bank_genderOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsms_count_bank_genderOperationCompleted);
            }
            this.InvokeAsync("sms_count_bank_gender", new object[] {
                        parentid,
                        dargah}, this.sms_count_bank_genderOperationCompleted, userState);
        }
        
        private void Onsms_count_bank_genderOperationCompleted(object arg) {
            if ((this.sms_count_bank_genderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sms_count_bank_genderCompleted(this, new sms_count_bank_genderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("sms_webservice_wsdl#user_add_cat", RequestNamespace="sms_webservice_wsdl", ResponseNamespace="sms_webservice_wsdl")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public long[] user_add_cat(string username, string password, string[] title) {
            object[] results = this.Invoke("user_add_cat", new object[] {
                        username,
                        password,
                        title});
            return ((long[])(results[0]));
        }
        
        /// <remarks/>
        public void user_add_catAsync(string username, string password, string[] title) {
            this.user_add_catAsync(username, password, title, null);
        }
        
        /// <remarks/>
        public void user_add_catAsync(string username, string password, string[] title, object userState) {
            if ((this.user_add_catOperationCompleted == null)) {
                this.user_add_catOperationCompleted = new System.Threading.SendOrPostCallback(this.Onuser_add_catOperationCompleted);
            }
            this.InvokeAsync("user_add_cat", new object[] {
                        username,
                        password,
                        title}, this.user_add_catOperationCompleted, userState);
        }
        
        private void Onuser_add_catOperationCompleted(object arg) {
            if ((this.user_add_catCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.user_add_catCompleted(this, new user_add_catCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("sms_webservice_wsdl#convert_unixtime_to_jalali", RequestNamespace="sms_webservice_wsdl", ResponseNamespace="sms_webservice_wsdl")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string convert_unixtime_to_jalali(int date) {
            object[] results = this.Invoke("convert_unixtime_to_jalali", new object[] {
                        date});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void convert_unixtime_to_jalaliAsync(int date) {
            this.convert_unixtime_to_jalaliAsync(date, null);
        }
        
        /// <remarks/>
        public void convert_unixtime_to_jalaliAsync(int date, object userState) {
            if ((this.convert_unixtime_to_jalaliOperationCompleted == null)) {
                this.convert_unixtime_to_jalaliOperationCompleted = new System.Threading.SendOrPostCallback(this.Onconvert_unixtime_to_jalaliOperationCompleted);
            }
            this.InvokeAsync("convert_unixtime_to_jalali", new object[] {
                        date}, this.convert_unixtime_to_jalaliOperationCompleted, userState);
        }
        
        private void Onconvert_unixtime_to_jalaliOperationCompleted(object arg) {
            if ((this.convert_unixtime_to_jalaliCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.convert_unixtime_to_jalaliCompleted(this, new convert_unixtime_to_jalaliCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("sms_webservice_wsdl#number_query", RequestNamespace="sms_webservice_wsdl", ResponseNamespace="sms_webservice_wsdl")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string number_query(string number) {
            object[] results = this.Invoke("number_query", new object[] {
                        number});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void number_queryAsync(string number) {
            this.number_queryAsync(number, null);
        }
        
        /// <remarks/>
        public void number_queryAsync(string number, object userState) {
            if ((this.number_queryOperationCompleted == null)) {
                this.number_queryOperationCompleted = new System.Threading.SendOrPostCallback(this.Onnumber_queryOperationCompleted);
            }
            this.InvokeAsync("number_query", new object[] {
                        number}, this.number_queryOperationCompleted, userState);
        }
        
        private void Onnumber_queryOperationCompleted(object arg) {
            if ((this.number_queryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.number_queryCompleted(this, new number_queryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("sms_webservice_wsdl#convert_jalali_to_unixtimestamp", RequestNamespace="sms_webservice_wsdl", ResponseNamespace="sms_webservice_wsdl")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string convert_jalali_to_unixtimestamp(int year, int month, int day, int hour, int minute) {
            object[] results = this.Invoke("convert_jalali_to_unixtimestamp", new object[] {
                        year,
                        month,
                        day,
                        hour,
                        minute});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void convert_jalali_to_unixtimestampAsync(int year, int month, int day, int hour, int minute) {
            this.convert_jalali_to_unixtimestampAsync(year, month, day, hour, minute, null);
        }
        
        /// <remarks/>
        public void convert_jalali_to_unixtimestampAsync(int year, int month, int day, int hour, int minute, object userState) {
            if ((this.convert_jalali_to_unixtimestampOperationCompleted == null)) {
                this.convert_jalali_to_unixtimestampOperationCompleted = new System.Threading.SendOrPostCallback(this.Onconvert_jalali_to_unixtimestampOperationCompleted);
            }
            this.InvokeAsync("convert_jalali_to_unixtimestamp", new object[] {
                        year,
                        month,
                        day,
                        hour,
                        minute}, this.convert_jalali_to_unixtimestampOperationCompleted, userState);
        }
        
        private void Onconvert_jalali_to_unixtimestampOperationCompleted(object arg) {
            if ((this.convert_jalali_to_unixtimestampCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.convert_jalali_to_unixtimestampCompleted(this, new convert_jalali_to_unixtimestampCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("sms_webservice_wsdl#admin_allow_number_new", RequestNamespace="sms_webservice_wsdl", ResponseNamespace="sms_webservice_wsdl")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public array_number_state[] admin_allow_number_new(string username, string password, string[] adminid, string[] number, string[] dargah) {
            object[] results = this.Invoke("admin_allow_number_new", new object[] {
                        username,
                        password,
                        adminid,
                        number,
                        dargah});
            return ((array_number_state[])(results[0]));
        }
        
        /// <remarks/>
        public void admin_allow_number_newAsync(string username, string password, string[] adminid, string[] number, string[] dargah) {
            this.admin_allow_number_newAsync(username, password, adminid, number, dargah, null);
        }
        
        /// <remarks/>
        public void admin_allow_number_newAsync(string username, string password, string[] adminid, string[] number, string[] dargah, object userState) {
            if ((this.admin_allow_number_newOperationCompleted == null)) {
                this.admin_allow_number_newOperationCompleted = new System.Threading.SendOrPostCallback(this.Onadmin_allow_number_newOperationCompleted);
            }
            this.InvokeAsync("admin_allow_number_new", new object[] {
                        username,
                        password,
                        adminid,
                        number,
                        dargah}, this.admin_allow_number_newOperationCompleted, userState);
        }
        
        private void Onadmin_allow_number_newOperationCompleted(object arg) {
            if ((this.admin_allow_number_newCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.admin_allow_number_newCompleted(this, new admin_allow_number_newCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:sms_webservice_wsdl")]
    public partial class array_number_in_cat {
        
        private string idField;
        
        private string fullnameField;
        
        private string numberField;
        
        private string dateField;
        
        private string genderField;
        
        private string fullname_enField;
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string fullname {
            get {
                return this.fullnameField;
            }
            set {
                this.fullnameField = value;
            }
        }
        
        /// <remarks/>
        public string number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        public string date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        public string gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        public string fullname_en {
            get {
                return this.fullname_enField;
            }
            set {
                this.fullname_enField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:sms_webservice_wsdl")]
    public partial class array_tree {
        
        private int idField;
        
        private string nameField;
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:sms_webservice_wsdl")]
    public partial class array_receive {
        
        private string idField;
        
        private string sender_numberField;
        
        private string receiver_numberField;
        
        private string dateField;
        
        private string catidField;
        
        private string noteField;
        
        private int readField;
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string sender_number {
            get {
                return this.sender_numberField;
            }
            set {
                this.sender_numberField = value;
            }
        }
        
        /// <remarks/>
        public string receiver_number {
            get {
                return this.receiver_numberField;
            }
            set {
                this.receiver_numberField = value;
            }
        }
        
        /// <remarks/>
        public string date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        public string catid {
            get {
                return this.catidField;
            }
            set {
                this.catidField = value;
            }
        }
        
        /// <remarks/>
        public string note {
            get {
                return this.noteField;
            }
            set {
                this.noteField = value;
            }
        }
        
        /// <remarks/>
        public int read {
            get {
                return this.readField;
            }
            set {
                this.readField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:sms_webservice_wsdl")]
    public partial class return_array_user_info {
        
        private string idField;
        
        private string fullnameField;
        
        private string emailField;
        
        private string mobileField;
        
        private string cashField;
        
        private string dateField;
        
        private string date_expireField;
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string fullname {
            get {
                return this.fullnameField;
            }
            set {
                this.fullnameField = value;
            }
        }
        
        /// <remarks/>
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string mobile {
            get {
                return this.mobileField;
            }
            set {
                this.mobileField = value;
            }
        }
        
        /// <remarks/>
        public string cash {
            get {
                return this.cashField;
            }
            set {
                this.cashField = value;
            }
        }
        
        /// <remarks/>
        public string date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        public string date_expire {
            get {
                return this.date_expireField;
            }
            set {
                this.date_expireField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:sms_webservice_wsdl")]
    public partial class array_number_state {
        
        private string numberField;
        
        private string stateField;
        
        /// <remarks/>
        public string number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        public string state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:sms_webservice_wsdl")]
    public partial class array_number {
        
        private string numberField;
        
        private string orderField;
        
        private string kindField;
        
        /// <remarks/>
        public string number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        public string order {
            get {
                return this.orderField;
            }
            set {
                this.orderField = value;
            }
        }
        
        /// <remarks/>
        public string kind {
            get {
                return this.kindField;
            }
            set {
                this.kindField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:sms_webservice_wsdl")]
    public partial class array_cat_list {
        
        private string idField;
        
        private string titleField;
        
        private string dateField;
        
        private int numberField;
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        public int number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void sms_get_number_in_catCompletedEventHandler(object sender, sms_get_number_in_catCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sms_get_number_in_catCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sms_get_number_in_catCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public array_number_in_cat[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((array_number_in_cat[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void sms_get_cat_listCompletedEventHandler(object sender, sms_get_cat_listCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sms_get_cat_listCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sms_get_cat_listCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public array_cat_list[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((array_cat_list[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void send_smsCompletedEventHandler(object sender, send_smsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class send_smsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal send_smsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void get_numberCompletedEventHandler(object sender, get_numberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_numberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_numberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public array_number[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((array_number[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void sms_deliverCompletedEventHandler(object sender, sms_deliverCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sms_deliverCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sms_deliverCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public long[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void is_number_in_blacklistCompletedEventHandler(object sender, is_number_in_blacklistCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class is_number_in_blacklistCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal is_number_in_blacklistCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public array_number_state[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((array_number_state[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void add_userCompletedEventHandler(object sender, add_userCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class add_userCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal add_userCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void sms_user_infoCompletedEventHandler(object sender, sms_user_infoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sms_user_infoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sms_user_infoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public return_array_user_info Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((return_array_user_info)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void sms_creditCompletedEventHandler(object sender, sms_creditCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sms_creditCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sms_creditCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void sms_add_numberCompletedEventHandler(object sender, sms_add_numberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sms_add_numberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sms_add_numberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void sms_receiveCompletedEventHandler(object sender, sms_receiveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sms_receiveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sms_receiveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public array_receive[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((array_receive[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void sms_receive_change_readCompletedEventHandler(object sender, sms_receive_change_readCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sms_receive_change_readCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sms_receive_change_readCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void sms_count_bulk_genderCompletedEventHandler(object sender, sms_count_bulk_genderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sms_count_bulk_genderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sms_count_bulk_genderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void sms_send_bulk_genderCompletedEventHandler(object sender, sms_send_bulk_genderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sms_send_bulk_genderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sms_send_bulk_genderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void sms_count_bank_genderCompletedEventHandler(object sender, sms_count_bank_genderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sms_count_bank_genderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sms_count_bank_genderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public array_tree[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((array_tree[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void user_add_catCompletedEventHandler(object sender, user_add_catCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class user_add_catCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal user_add_catCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public long[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void convert_unixtime_to_jalaliCompletedEventHandler(object sender, convert_unixtime_to_jalaliCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class convert_unixtime_to_jalaliCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal convert_unixtime_to_jalaliCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void number_queryCompletedEventHandler(object sender, number_queryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class number_queryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal number_queryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void convert_jalali_to_unixtimestampCompletedEventHandler(object sender, convert_jalali_to_unixtimestampCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class convert_jalali_to_unixtimestampCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal convert_jalali_to_unixtimestampCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void admin_allow_number_newCompletedEventHandler(object sender, admin_allow_number_newCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class admin_allow_number_newCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal admin_allow_number_newCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public array_number_state[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((array_number_state[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591