//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarProject.arianpalWebservice {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentRequestResult", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class PaymentRequestResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentPathField;
        
        private CarProject.arianpalWebservice.ResultValues ResultStatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PaymentPath {
            get {
                return this.PaymentPathField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentPathField, value) != true)) {
                    this.PaymentPathField = value;
                    this.RaisePropertyChanged("PaymentPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public CarProject.arianpalWebservice.ResultValues ResultStatus {
            get {
                return this.ResultStatusField;
            }
            set {
                if ((this.ResultStatusField.Equals(value) != true)) {
                    this.ResultStatusField = value;
                    this.RaisePropertyChanged("ResultStatus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultValues", Namespace="http://tempuri.org/")]
    public enum ResultValues : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ready = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GatewayUnverify = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GatewayIsExpired = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GatewayIsBlocked = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GatewayInvalidInfo = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserNotActive = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidServerIP = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Succeed = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failed = 8,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VerifyPaymentResult", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class VerifyPaymentResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private CarProject.arianpalWebservice.VerifyResult ResultStatusField;
        
        private decimal PayementedPriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public CarProject.arianpalWebservice.VerifyResult ResultStatus {
            get {
                return this.ResultStatusField;
            }
            set {
                if ((this.ResultStatusField.Equals(value) != true)) {
                    this.ResultStatusField = value;
                    this.RaisePropertyChanged("ResultStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public decimal PayementedPrice {
            get {
                return this.PayementedPriceField;
            }
            set {
                if ((this.PayementedPriceField.Equals(value) != true)) {
                    this.PayementedPriceField = value;
                    this.RaisePropertyChanged("PayementedPrice");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VerifyResult", Namespace="http://tempuri.org/")]
    public enum VerifyResult : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ready = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotMatchMoney = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Verifyed = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidRef = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GatewayInvalidInfo = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="arianpalWebservice.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name MerchantID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RequestPayment", ReplyAction="*")]
        CarProject.arianpalWebservice.RequestPaymentResponse RequestPayment(CarProject.arianpalWebservice.RequestPaymentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RequestPayment", ReplyAction="*")]
        System.Threading.Tasks.Task<CarProject.arianpalWebservice.RequestPaymentResponse> RequestPaymentAsync(CarProject.arianpalWebservice.RequestPaymentRequest request);
        
        // CODEGEN: Generating message contract since element name MerchantID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/verifyPayment", ReplyAction="*")]
        CarProject.arianpalWebservice.verifyPaymentResponse verifyPayment(CarProject.arianpalWebservice.verifyPaymentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/verifyPayment", ReplyAction="*")]
        System.Threading.Tasks.Task<CarProject.arianpalWebservice.verifyPaymentResponse> verifyPaymentAsync(CarProject.arianpalWebservice.verifyPaymentRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RequestPaymentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RequestPayment", Namespace="http://tempuri.org/", Order=0)]
        public CarProject.arianpalWebservice.RequestPaymentRequestBody Body;
        
        public RequestPaymentRequest() {
        }
        
        public RequestPaymentRequest(CarProject.arianpalWebservice.RequestPaymentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RequestPaymentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MerchantID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public decimal Price;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Description;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Paymenter;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Mobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string ResNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string ReturnPath;
        
        public RequestPaymentRequestBody() {
        }
        
        public RequestPaymentRequestBody(string MerchantID, string Password, decimal Price, string Description, string Paymenter, string Email, string Mobile, string ResNumber, string ReturnPath) {
            this.MerchantID = MerchantID;
            this.Password = Password;
            this.Price = Price;
            this.Description = Description;
            this.Paymenter = Paymenter;
            this.Email = Email;
            this.Mobile = Mobile;
            this.ResNumber = ResNumber;
            this.ReturnPath = ReturnPath;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RequestPaymentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RequestPaymentResponse", Namespace="http://tempuri.org/", Order=0)]
        public CarProject.arianpalWebservice.RequestPaymentResponseBody Body;
        
        public RequestPaymentResponse() {
        }
        
        public RequestPaymentResponse(CarProject.arianpalWebservice.RequestPaymentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RequestPaymentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CarProject.arianpalWebservice.PaymentRequestResult RequestPaymentResult;
        
        public RequestPaymentResponseBody() {
        }
        
        public RequestPaymentResponseBody(CarProject.arianpalWebservice.PaymentRequestResult RequestPaymentResult) {
            this.RequestPaymentResult = RequestPaymentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class verifyPaymentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="verifyPayment", Namespace="http://tempuri.org/", Order=0)]
        public CarProject.arianpalWebservice.verifyPaymentRequestBody Body;
        
        public verifyPaymentRequest() {
        }
        
        public verifyPaymentRequest(CarProject.arianpalWebservice.verifyPaymentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class verifyPaymentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MerchantID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public decimal Price;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string RefNum;
        
        public verifyPaymentRequestBody() {
        }
        
        public verifyPaymentRequestBody(string MerchantID, string Password, decimal Price, string RefNum) {
            this.MerchantID = MerchantID;
            this.Password = Password;
            this.Price = Price;
            this.RefNum = RefNum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class verifyPaymentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="verifyPaymentResponse", Namespace="http://tempuri.org/", Order=0)]
        public CarProject.arianpalWebservice.verifyPaymentResponseBody Body;
        
        public verifyPaymentResponse() {
        }
        
        public verifyPaymentResponse(CarProject.arianpalWebservice.verifyPaymentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class verifyPaymentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CarProject.arianpalWebservice.VerifyPaymentResult verifyPaymentResult;
        
        public verifyPaymentResponseBody() {
        }
        
        public verifyPaymentResponseBody(CarProject.arianpalWebservice.VerifyPaymentResult verifyPaymentResult) {
            this.verifyPaymentResult = verifyPaymentResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : CarProject.arianpalWebservice.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<CarProject.arianpalWebservice.WebServiceSoap>, CarProject.arianpalWebservice.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarProject.arianpalWebservice.RequestPaymentResponse CarProject.arianpalWebservice.WebServiceSoap.RequestPayment(CarProject.arianpalWebservice.RequestPaymentRequest request) {
            return base.Channel.RequestPayment(request);
        }
        
        public CarProject.arianpalWebservice.PaymentRequestResult RequestPayment(string MerchantID, string Password, decimal Price, string Description, string Paymenter, string Email, string Mobile, string ResNumber, string ReturnPath) {
            CarProject.arianpalWebservice.RequestPaymentRequest inValue = new CarProject.arianpalWebservice.RequestPaymentRequest();
            inValue.Body = new CarProject.arianpalWebservice.RequestPaymentRequestBody();
            inValue.Body.MerchantID = MerchantID;
            inValue.Body.Password = Password;
            inValue.Body.Price = Price;
            inValue.Body.Description = Description;
            inValue.Body.Paymenter = Paymenter;
            inValue.Body.Email = Email;
            inValue.Body.Mobile = Mobile;
            inValue.Body.ResNumber = ResNumber;
            inValue.Body.ReturnPath = ReturnPath;
            CarProject.arianpalWebservice.RequestPaymentResponse retVal = ((CarProject.arianpalWebservice.WebServiceSoap)(this)).RequestPayment(inValue);
            return retVal.Body.RequestPaymentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarProject.arianpalWebservice.RequestPaymentResponse> CarProject.arianpalWebservice.WebServiceSoap.RequestPaymentAsync(CarProject.arianpalWebservice.RequestPaymentRequest request) {
            return base.Channel.RequestPaymentAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarProject.arianpalWebservice.RequestPaymentResponse> RequestPaymentAsync(string MerchantID, string Password, decimal Price, string Description, string Paymenter, string Email, string Mobile, string ResNumber, string ReturnPath) {
            CarProject.arianpalWebservice.RequestPaymentRequest inValue = new CarProject.arianpalWebservice.RequestPaymentRequest();
            inValue.Body = new CarProject.arianpalWebservice.RequestPaymentRequestBody();
            inValue.Body.MerchantID = MerchantID;
            inValue.Body.Password = Password;
            inValue.Body.Price = Price;
            inValue.Body.Description = Description;
            inValue.Body.Paymenter = Paymenter;
            inValue.Body.Email = Email;
            inValue.Body.Mobile = Mobile;
            inValue.Body.ResNumber = ResNumber;
            inValue.Body.ReturnPath = ReturnPath;
            return ((CarProject.arianpalWebservice.WebServiceSoap)(this)).RequestPaymentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarProject.arianpalWebservice.verifyPaymentResponse CarProject.arianpalWebservice.WebServiceSoap.verifyPayment(CarProject.arianpalWebservice.verifyPaymentRequest request) {
            return base.Channel.verifyPayment(request);
        }
        
        public CarProject.arianpalWebservice.VerifyPaymentResult verifyPayment(string MerchantID, string Password, decimal Price, string RefNum) {
            CarProject.arianpalWebservice.verifyPaymentRequest inValue = new CarProject.arianpalWebservice.verifyPaymentRequest();
            inValue.Body = new CarProject.arianpalWebservice.verifyPaymentRequestBody();
            inValue.Body.MerchantID = MerchantID;
            inValue.Body.Password = Password;
            inValue.Body.Price = Price;
            inValue.Body.RefNum = RefNum;
            CarProject.arianpalWebservice.verifyPaymentResponse retVal = ((CarProject.arianpalWebservice.WebServiceSoap)(this)).verifyPayment(inValue);
            return retVal.Body.verifyPaymentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarProject.arianpalWebservice.verifyPaymentResponse> CarProject.arianpalWebservice.WebServiceSoap.verifyPaymentAsync(CarProject.arianpalWebservice.verifyPaymentRequest request) {
            return base.Channel.verifyPaymentAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarProject.arianpalWebservice.verifyPaymentResponse> verifyPaymentAsync(string MerchantID, string Password, decimal Price, string RefNum) {
            CarProject.arianpalWebservice.verifyPaymentRequest inValue = new CarProject.arianpalWebservice.verifyPaymentRequest();
            inValue.Body = new CarProject.arianpalWebservice.verifyPaymentRequestBody();
            inValue.Body.MerchantID = MerchantID;
            inValue.Body.Password = Password;
            inValue.Body.Price = Price;
            inValue.Body.RefNum = RefNum;
            return ((CarProject.arianpalWebservice.WebServiceSoap)(this)).verifyPaymentAsync(inValue);
        }
    }
}
