//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarProject.DBSEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AirConditioningSystemDetail
    {
        public int AirConditioningSystemDetailId { get; set; }
        public string AirConditioningSystemDetailSubject { get; set; }
        public string AirConditioningSystemDetail1 { get; set; }
        public Nullable<int> CarsId { get; set; }
    
        public virtual Car Car { get; set; }
    }
}
