//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarProject.DBSEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoService
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AutoService()
        {
            this.AutoServiceCars = new HashSet<AutoServiceCar>();
            this.AutoServices = new HashSet<AutoService1>();
            this.AutoServicesUserComments = new HashSet<AutoServicesUserComment>();
            this.PersonServices = new HashSet<PersonService>();
            this.PersonServicesUseRequests = new HashSet<PersonServicesUseRequest>();
            this.ProductDiscounts = new HashSet<ProductDiscount>();
            this.ProductInServices = new HashSet<ProductInService>();
            this.ServiceToViews = new HashSet<ServiceToView>();
            this.UserAutoServices = new HashSet<UserAutoService>();
        }
    
        public int AutoServiceId { get; set; }
        public string AutoServiceName { get; set; }
        public Nullable<bool> HasCarId { get; set; }
        public Nullable<bool> HasProduct { get; set; }
        public string Price { get; set; }
        public Nullable<int> ServicesCategoryId { get; set; }
        public string AutoServiceDescription { get; set; }
        public string AutoServiceEnglishName { get; set; }
    
        public virtual ServicesCategory ServicesCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutoServiceCar> AutoServiceCars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutoService1> AutoServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutoServicesUserComment> AutoServicesUserComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonService> PersonServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonServicesUseRequest> PersonServicesUseRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductDiscount> ProductDiscounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductInService> ProductInServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceToView> ServiceToViews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserAutoService> UserAutoServices { get; set; }
    }
}
