//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarProject.DBSEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoServicePackUserComment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AutoServicePackUserComment()
        {
            this.AutoServicePackUserComments1 = new HashSet<AutoServicePackUserComment>();
        }
    
        public int AutoServicePackUserCommentsId { get; set; }
        public Nullable<int> AutoServicePackID { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<int> rootAutoServicePackUserCommentsId { get; set; }
    
        public virtual AutoServicePack AutoServicePack { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutoServicePackUserComment> AutoServicePackUserComments1 { get; set; }
        public virtual AutoServicePackUserComment AutoServicePackUserComment1 { get; set; }
        public virtual User User { get; set; }
    }
}
