//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarProject.DBSEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoService
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AutoService()
        {
            this.AutoServices = new HashSet<AutoService1>();
            this.PersonProducts = new HashSet<PersonProduct>();
        }
    
        public int AutoServiceId { get; set; }
        public string AutoServiceName { get; set; }
        public Nullable<bool> HasCarId { get; set; }
        public Nullable<int> CarId { get; set; }
        public Nullable<bool> HasProduct { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string Price { get; set; }
        public Nullable<int> DiscountId { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Discount Discount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutoService1> AutoServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonProduct> PersonProducts { get; set; }
    }
}
