
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CarProject.DBSEF
{

using System;
    using System.Collections.Generic;
    
public partial class AutoServicePack
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public AutoServicePack()
    {

        this.AutoServices = new HashSet<AutoService1>();

        this.PersonProducts = new HashSet<PersonProduct>();

    }


    public int AutoServicePackId { get; set; }

    public string AutoServicePackName { get; set; }

    public string PackPrice { get; set; }

    public Nullable<bool> HasDiscount { get; set; }

    public Nullable<int> DicsountId { get; set; }



    public virtual Discount Discount { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AutoService1> AutoServices { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PersonProduct> PersonProducts { get; set; }

}

}
