//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace CarProject.DBSEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrakeSystem
    {
        public int BrakeSystemId { get; set; }
       
        public Nullable<int> CarId { get; set; }
        [DisplayName("سیستم ترمز چرخ جلو")]
        public string FrontBrakeSystem { get; set; }
        [DisplayName("سیستم ترمز چرخ عقب")]
        public string RearBrakeSystem { get; set; }
        [DisplayName("سیستم های دیگر")]
        public string OtherSystem { get; set; }
        [DisplayName("ترمز دستی")]
        public string HandBrakeSystem { get; set; }
        [DisplayName("توضیحات")]
        public string Details { get; set; }
    
        public virtual Car Car { get; set; }
    }
}
