//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarProject.DBSEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Car()
        {
            this.AirConditioningSystems = new HashSet<AirConditioningSystem>();
            this.AirConditioningSystemDetails = new HashSet<AirConditioningSystemDetail>();
            this.AutoServiceCars = new HashSet<AutoServiceCar>();
            this.BrakeSystems = new HashSet<BrakeSystem>();
            this.CarAirbags = new HashSet<CarAirbag>();
            this.CarAudioSystems = new HashSet<CarAudioSystem>();
            this.CarComments = new HashSet<CarComment>();
            this.CarDetails = new HashSet<CarDetail>();
            this.CarEngines = new HashSet<CarEngine>();
            this.CarGearBoxes = new HashSet<CarGearBox>();
            this.CarLightingSystems = new HashSet<CarLightingSystem>();
            this.CarPhysicalDetails = new HashSet<CarPhysicalDetail>();
            this.CarPrices = new HashSet<CarPrice>();
            this.CarSeatOptions = new HashSet<CarSeatOption>();
            this.CarSensorsSystems = new HashSet<CarSensorsSystem>();
            this.CarsInSameClasses = new HashSet<CarsInSameClass>();
            this.CarsInSameClasses1 = new HashSet<CarsInSameClass>();
            this.CarsProes = new HashSet<CarsPro>();
            this.CarsQnAs = new HashSet<CarsQnA>();
            this.CarsReviews = new HashSet<CarsReview>();
            this.CarsReviewPoints = new HashSet<CarsReviewPoint>();
            this.CarsToViews = new HashSet<CarsToView>();
            this.CarUserComments = new HashSet<CarUserComment>();
            this.CarWheels = new HashSet<CarWheel>();
            this.DetailedBrakeSystems = new HashSet<DetailedBrakeSystem>();
            this.FuelConsumptions = new HashSet<FuelConsumption>();
            this.GlassAndMirrors = new HashSet<GlassAndMirror>();
            this.PersonCars = new HashSet<PersonCar>();
            this.Products = new HashSet<Product>();
            this.ProductCars = new HashSet<ProductCar>();
            this.SecuritySystems = new HashSet<SecuritySystem>();
            this.SteeringSystems = new HashSet<SteeringSystem>();
        }
    
        public int CarsId { get; set; }
        public Nullable<int> CarModelId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string CarsClass { get; set; }
        public Nullable<double> CarsUserScore { get; set; }
        public Nullable<double> CarsClinicScore { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> CarsPicsId { get; set; }
        public string CarsVideoURL { get; set; }
        public string CarsDescription { get; set; }
        public string CarClassType { get; set; }
        public string CarCategory { get; set; }
        public string CarUsage { get; set; }
        public Nullable<int> CarYearModel { get; set; }
        public string CarBodyType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AirConditioningSystem> AirConditioningSystems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AirConditioningSystemDetail> AirConditioningSystemDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutoServiceCar> AutoServiceCars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BrakeSystem> BrakeSystems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarAirbag> CarAirbags { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarAudioSystem> CarAudioSystems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarComment> CarComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarDetail> CarDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarEngine> CarEngines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarGearBox> CarGearBoxes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarLightingSystem> CarLightingSystems { get; set; }
        public virtual CarModel CarModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarPhysicalDetail> CarPhysicalDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarPrice> CarPrices { get; set; }
        public virtual Country Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarSeatOption> CarSeatOptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarSensorsSystem> CarSensorsSystems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarsInSameClass> CarsInSameClasses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarsInSameClass> CarsInSameClasses1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarsPro> CarsProes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarsQnA> CarsQnAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarsReview> CarsReviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarsReviewPoint> CarsReviewPoints { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarsToView> CarsToViews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarUserComment> CarUserComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarWheel> CarWheels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailedBrakeSystem> DetailedBrakeSystems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FuelConsumption> FuelConsumptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GlassAndMirror> GlassAndMirrors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonCar> PersonCars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductCar> ProductCars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SecuritySystem> SecuritySystems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SteeringSystem> SteeringSystems { get; set; }
    }
}
