//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace CarProject.DBSEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarAudioSystem
    {
        public int CarAudioSystemId { get; set; }
        [DisplayName("نوع سیستم صوتی")]
        public string AudioSystemType { get; set; }
        [DisplayName("برند سیستم صوتی")]
        public string AudioSystemBrand { get; set; }
        [DisplayName("دارای مانیتور ؟")]
        public Nullable<bool> HasMonitor { get; set; }
        [DisplayName("مانیتور صندلی عقب")]
        public Nullable<bool> RearSeatsMonitor { get; set; }
        [DisplayName("دوربین دنده عقب")]
        public Nullable<bool> RearGearCamera { get; set; }
        [DisplayName("دوربین جلو")]
        public Nullable<bool> FrontCamera { get; set; }
        [DisplayName("سیستم صوتی عقب")]
        public string RearStereo { get; set; }
        [DisplayName("سیستم صوتی جلو")]
        public string FrontStereo { get; set; }
        [DisplayName("ساب ووفر")]
        public string Subwoofer { get; set; }
        [DisplayName("آمپلیفایر")]
        public string Amplifire { get; set; }
        [DisplayName("دارای سیستم ناوبری")]
        public Nullable<bool> HasGps { get; set; }
        [DisplayName("توضیحات")]
        public string Details { get; set; }
        public int CarsId { get; set; }
    
        public virtual Car Car { get; set; }
    }
}
