//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarProject.DBSEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarAirbag
    {
        public int CarAirbagsId { get; set; }
        public Nullable<bool> DriverAirBag { get; set; }
        public Nullable<bool> FrontAirBag { get; set; }
        public Nullable<bool> AirBag { get; set; }
        public Nullable<int> AirBagEntity { get; set; }
        public string Details { get; set; }
        public Nullable<int> CarsId { get; set; }
    
        public virtual Car Car { get; set; }
    }
}
