//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarProject.DBSEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarAudioSystem
    {
        public int CarAudioSystemId { get; set; }
        public string AudioSystemType { get; set; }
        public string AudioSystemBrand { get; set; }
        public Nullable<bool> HasMonitor { get; set; }
        public Nullable<bool> RearSeatsMonitor { get; set; }
        public Nullable<bool> RearGearCamera { get; set; }
        public Nullable<bool> FrontCamera { get; set; }
        public string RearStereo { get; set; }
        public string FrontStereo { get; set; }
        public string Subwoofer { get; set; }
        public string Amplifire { get; set; }
        public Nullable<bool> HasGps { get; set; }
        public string Details { get; set; }
        public int CarsId { get; set; }
    
        public virtual Car Car { get; set; }
    }
}
