//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarProject.DBSEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarDetail
    {
        public int CarDetailsId { get; set; }
        public Nullable<int> CarsId { get; set; }
        public Nullable<int> OilChangeDate { get; set; }
        public Nullable<int> OilChangeMilage { get; set; }
        public Nullable<int> OilFiltersChangeDate { get; set; }
        public Nullable<int> OilFilterChangeMilage { get; set; }
        public Nullable<int> GearBoxOilChangeDate { get; set; }
        public Nullable<int> GearBoxOilChangeMilage { get; set; }
        public Nullable<int> AirFilterChangeDate { get; set; }
        public Nullable<int> AirFilterChangeMilage { get; set; }
        public Nullable<int> TiresChangeDate { get; set; }
        public Nullable<int> TiresChangeMilage { get; set; }
        public Nullable<int> TimingbeltChangeDate { get; set; }
        public Nullable<int> TimingbeltChangeMilage { get; set; }
        public Nullable<int> OtherBeltsChangeDate { get; set; }
        public Nullable<int> OtherBeltsChangeMilage { get; set; }
        public Nullable<int> FrontBrakePadsChangeDate { get; set; }
        public Nullable<int> FrontBrakePadsChangeMilage { get; set; }
        public Nullable<int> RearBreakePadsChangeDate { get; set; }
        public Nullable<int> RearBrakePadsChangeMilage { get; set; }
    
        public virtual Car Car { get; set; }
    }
}
