//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace CarProject.DBSEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarEngine
    {
        public int CarEngineId { get; set; }
        [DisplayName("نوع موتور")]

        public string EngineType { get; set; }
        [DisplayName("تعداد سیلندر")]
        public Nullable<int> EngineCylinderNumber { get; set; }
        [DisplayName("قدرت موتور")]
        public Nullable<int> EnginePowerHpRpm { get; set; }
        [DisplayName("گشتاور")]
        public Nullable<int> EngineTorque { get; set; }
        [DisplayName("توان وزنی")]
        public Nullable<int> EnginePowerHpTon { get; set; }
        [DisplayName("توان خروجی")]
        public Nullable<int> EnginePowerHpLitr { get; set; }
        [DisplayName("حداکثر سرعت")]
        public Nullable<int> EngineMaxSpeed { get; set; }
        [DisplayName("صفر تا صد کلیومتر")]
        public Nullable<int> EngineZeroToH { get; set; }
        [DisplayName("توضیحات")]
        public string EngineDescription { get; set; }
        public Nullable<int> CarsId { get; set; }
    
        public virtual Car Car { get; set; }
    }
}
