//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace CarProject.DBSEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarGearBox
    {
        public int CarGearBoxId { get; set; }
        [DisplayName("کد گیربکس")]
        public string GearBoxCode { get; set; }
        [DisplayName("نوع گیربکس")]
        public string GearBoxType { get; set; }
        [DisplayName("آیا میتواند به صورت دستی تعویض شود ؟")]
        public Nullable<bool> GearBoxCanBeManual { get; set; }
        [DisplayName("تعداد دنده")]
        public Nullable<int> GearBoxShiftNumber { get; set; }
        [DisplayName("محور جابه جایی")]
        public string GearBoxAxel { get; set; }
        [DisplayName("آیا دارای جعبه انتقال قدرت است ؟")]
        public Nullable<bool> HasTransferCase { get; set; }
        [DisplayName("آیا قفل دفرانسیل دارد ؟")]
        public Nullable<bool> GearBoxDiffrentionalLock { get; set; }
        [DisplayName("نوع چهار چرخ")]
        public string GearBoxWdType { get; set; }
        [DisplayName("توضیحات")]
        public string GearBoxDescription { get; set; }
        public Nullable<int> CarsId { get; set; }
    
        public virtual Car Car { get; set; }
    }
}
