//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace CarProject.DBSEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarLightingSystem
    {
        public int CarLightingSystemId { get; set; }
        [DisplayName("سیستم چراغ های جلو")]
        public string FrontLights { get; set; }
        [DisplayName("سیستم چراغ های عقب")]
        public string RearLights { get; set; }
        [DisplayName("دیلایت")]
        public Nullable<bool> DayLight { get; set; }
        [DisplayName("چراغ راهنما روی راهنمای بقل")]
        public Nullable<bool> SideMirrorLight { get; set; }
        [DisplayName("مه شکن جلو")]
        public Nullable<bool> FonrAntiFog { get; set; }
        [DisplayName("مه شکن عقب")]
        public Nullable<bool> RearAntiFog { get; set; }

        //اینجا باید یه فیلد دیگه اضافه بشه

        [DisplayName("چراغ مطالعه")]
        public Nullable<bool> ReadingLamp { get; set; }
        [DisplayName("توضیحات")]
        public string Deailts { get; set; }
       
        public Nullable<int> CarsId { get; set; }
    
        public virtual Car Car { get; set; }
    }
}
