
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CarProject.DBSEF
{

using System;
    using System.Collections.Generic;
    
public partial class CarLightingSystem
{

    public int CarLightingSystemId { get; set; }

    public string FrontLights { get; set; }

    public string RearLights { get; set; }

    public Nullable<bool> DayLight { get; set; }

    public Nullable<bool> SideMirrorLight { get; set; }

    public Nullable<bool> FonrAntiFog { get; set; }

    public Nullable<bool> RearAntiFog { get; set; }

    public Nullable<bool> ReadingLamp { get; set; }

    public string Deailts { get; set; }

    public Nullable<int> CarsId { get; set; }

    public Nullable<bool> ThirdLightStop { get; set; }



    public virtual Car Car { get; set; }

}

}
