
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CarProject.DBSEF
{

using System;
    using System.Collections.Generic;
    
public partial class CarPhysicalDetail
{

    public int CarPhysicalDetailsId { get; set; }

    public Nullable<int> CarLength { get; set; }

    public Nullable<int> Carwidth { get; set; }

    public Nullable<int> CarHeight { get; set; }

    public Nullable<int> CarTrack { get; set; }

    public Nullable<int> CarWheelBase { get; set; }

    public Nullable<int> CarPureWeight { get; set; }

    public Nullable<int> CarTankSize { get; set; }

    public string Details { get; set; }

    public Nullable<int> CarId { get; set; }



    public virtual Car Car { get; set; }

}

}
