//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace CarProject.DBSEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarPhysicalDetail
    {
        public int CarPhysicalDetailsId { get; set; }
        [DisplayName("طول خودرو")]
        public Nullable<int> CarLength { get; set; }
        [DisplayName("عرض خودرو")]
        public Nullable<int> Carwidth { get; set; }
        [DisplayName("ارتفاع خودرو")]
        public Nullable<int> CarHeight { get; set; }
        [DisplayName("فاصله دو چرخ (محور)")]
        public Nullable<int> CarTrack { get; set; }
        [DisplayName("فاصله دو محور")]
        public Nullable<int> CarWheelBase { get; set; }
        [DisplayName("وزن خالص")]
        public Nullable<int> CarPureWeight { get; set; }
        [DisplayName("حجم باک")]
        public Nullable<int> CarTankSize { get; set; }
        [DisplayName("توضیحات")]
        public string Details { get; set; }
        public Nullable<int> CarId { get; set; }
    
        public virtual Car Car { get; set; }
    }
}
