//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace CarProject.DBSEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarSensorsSystem
    {
        public int CarSensorsSystemId { get; set; }
        [DisplayName("سنسور روشنایی نور")]
        public Nullable<bool> DayLightSensor { get; set; }
        [DisplayName("سنسور باران")]
        public Nullable<bool> RainSensor { get; set; }
        [DisplayName("سنسور دنده عقب")]
        public Nullable<bool> RearGearSensor { get; set; }
        [DisplayName("سنسور پارک")]
        public Nullable<bool> ParkSensor { get; set; }
        [DisplayName("سنسور هدایت خودرو")]
        public Nullable<bool> NavigateSensor { get; set; }
        [DisplayName("کروز کنترل")]
        public Nullable<bool> CruiseControl { get; set; }
        [DisplayName("دوربین دنده عقب")]
        public Nullable<bool> RearGearCamera { get; set; }
        [DisplayName("توضیحات")]
        public string Details { get; set; }
        public Nullable<int> CarsId { get; set; }
    
        public virtual Car Car { get; set; }
    }
}
