
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CarProject.DBSEF
{

using System;
    using System.Collections.Generic;
    
public partial class CarsInSameClass
{

    public int CarsSameId { get; set; }

    public Nullable<int> CarsId { get; set; }

    public Nullable<int> CarsSameClassId { get; set; }



    public virtual Car Car { get; set; }

    public virtual Car Car1 { get; set; }

}

}
