//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarProject.DBSEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarSensorsSystem
    {
        public int CarSensorsSystemId { get; set; }
        public Nullable<bool> DayLightSensor { get; set; }
        public Nullable<bool> RainSensor { get; set; }
        public Nullable<bool> RearGearSensor { get; set; }
        public Nullable<bool> ParkSensor { get; set; }
        public Nullable<bool> NavigateSensor { get; set; }
        public Nullable<bool> CruiseControl { get; set; }
        public Nullable<bool> RearGearCamera { get; set; }
        public string Details { get; set; }
        public Nullable<int> CarsId { get; set; }
    
        public virtual Car Car { get; set; }
    }
}
