//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace CarProject.DBSEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarSeatOption
    {
        public int CarSeatOptionsId { get; set; }
        [DisplayName("جابه جایی طولی")]
        public string LongitudinalDisplacement { get; set; }
        [DisplayName("تنظیم گودی پشت کمر")]
        public Nullable<bool> BezelSet { get; set; }
        [DisplayName("گرم کن صندلی")]
        public Nullable<bool> SeatWarmer { get; set; }
        [DisplayName("ماساژور صندلی")]
        public Nullable<bool> SeatMassage { get; set; }
        [DisplayName("حافظه")]
        public Nullable<bool> HasMemory { get; set; }
        [DisplayName("توضیحات")]
        public string Details { get; set; }
        
        public int CarsId { get; set; }
    
        public virtual Car Car { get; set; }
    }
}
