//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarProject.DBSEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarSeatOption
    {
        public int CarSeatOptionsId { get; set; }
        public Nullable<bool> LongitudinalDisplacement { get; set; }
        public Nullable<bool> BezelSet { get; set; }
        public Nullable<bool> SeatWarmer { get; set; }
        public Nullable<bool> SeatMassage { get; set; }
        public Nullable<bool> HasMemory { get; set; }
        public string Details { get; set; }
        public int CarsId { get; set; }
    
        public virtual Car Car { get; set; }
    }
}
