//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarProject.DBSEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarsQnA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CarsQnA()
        {
            this.CarsQnA1 = new HashSet<CarsQnA>();
        }
    
        public int CarsQnAId { get; set; }
        public Nullable<int> CarsId { get; set; }
        public string QuestionType { get; set; }
        public string Question { get; set; }
        public Nullable<int> QuestionId { get; set; }
    
        public virtual Car Car { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarsQnA> CarsQnA1 { get; set; }
        public virtual CarsQnA CarsQnA2 { get; set; }
    }
}
