//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarProject.DBSEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarUserComment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CarUserComment()
        {
            this.CarUserComments1 = new HashSet<CarUserComment>();
        }
    
        public int CarUserCommentsId { get; set; }
        public Nullable<int> CarId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<int> RootCarUserCommentsId { get; set; }
        public Nullable<byte> CarRating { get; set; }
        public Nullable<byte> Beautifully { get; set; }
        public Nullable<byte> Worthly { get; set; }
        public Nullable<byte> Quality { get; set; }
        public Nullable<byte> Services { get; set; }
    
        public virtual Car Car { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarUserComment> CarUserComments1 { get; set; }
        public virtual CarUserComment CarUserComment1 { get; set; }
        public virtual User User { get; set; }
    }
}
