//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace CarProject.DBSEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarWheel
    {
        public int CarWheelsId { get; set; }
        public Nullable<int> CarsId { get; set; }
        [DisplayName("نوع لاستیک")]
        public string TireType { get; set; }
        [DisplayName("سایز رینگ استاندارد")]
        public Nullable<int> RingStandardSize { get; set; }
        [DisplayName("مشخصات لاستیک")]
        public string TireSpec { get; set; }
        [DisplayName("نوع رینگ")]
        public string RingType { get; set; }
        [DisplayName("مدل رینگ")]
        public string RingModel { get; set; }
        [DisplayName("قابلیت کم و زیاد کردن اتوماتیک بار تایر")]
        public Nullable<bool> AutoInflated { get; set; }
        [DisplayName("توضیحات")]
        public string Details { get; set; }
    
        public virtual Car Car { get; set; }
    }
}
