
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CarProject.DBSEF
{

using System;
    using System.Collections.Generic;
    
public partial class CarWheel
{

    public int CarWheelsId { get; set; }

    public Nullable<int> CarsId { get; set; }

    public string TireType { get; set; }

    public Nullable<int> RingStandardSize { get; set; }

    public string TireSpec { get; set; }

    public string RingType { get; set; }

    public string RingModel { get; set; }

    public Nullable<bool> AutoInflated { get; set; }

    public string Details { get; set; }



    public virtual Car Car { get; set; }

}

}
