//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarProject.DBSEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class FuelConsumption
    {
        public int FuelConsumptionId { get; set; }
        public Nullable<double> LphCity { get; set; }
        public Nullable<double> LphRoad { get; set; }
        public Nullable<double> LphMix { get; set; }
        public string Details { get; set; }
        public string ReservedOne { get; set; }
        public string ReservedTwo { get; set; }
        public string ReservedThree { get; set; }
        public Nullable<int> CarId { get; set; }
    
        public virtual Car Car { get; set; }
    }
}
