
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CarProject.DBSEF
{

using System;
    using System.Collections.Generic;
    
public partial class GlassAndMirror
{

    public int GlassAndMirrorsId { get; set; }

    public string FrontWindscreens { get; set; }

    public string RearWindscreens { get; set; }

    public Nullable<bool> SunRoof { get; set; }

    public Nullable<bool> PanaromaRoof { get; set; }

    public Nullable<bool> RearGlassWarmer { get; set; }

    public Nullable<bool> WindscreensWarmer { get; set; }

    public Nullable<bool> FrontGlassWarmer { get; set; }

    public string SideMirrorSet { get; set; }

    public string SideMirrorSystem { get; set; }

    public string Details { get; set; }

    public Nullable<int> CarsId { get; set; }



    public virtual Car Car { get; set; }

}

}
