//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace CarProject.DBSEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class GlassAndMirror
    {
        public int GlassAndMirrorsId { get; set; }
        [DisplayName("سیستم شیشه های جلو")]
        public string FrontWindscreens { get; set; }
        [DisplayName("سیستم شیشه های عقب")]
        public string RearWindscreens { get; set; }
        [DisplayName("سانروف")]
        public Nullable<bool> SunRoof { get; set; }
        [DisplayName("سقف پاناروما")]
        public Nullable<bool> PanaromaRoof { get; set; }
        [DisplayName("گرمکن شیشه عقب")]
        public Nullable<bool> RearGlassWarmer { get; set; }
        [DisplayName("گرمکن شیشه های بقل")]
        public Nullable<bool> WindscreensWarmer { get; set; }
        [DisplayName("گرمکن شیشه جلو")]
        public Nullable<bool> FrontGlassWarmer { get; set; }
        [DisplayName("تنظیم آینه های بقل")]
        public string SideMirrorSet { get; set; }
        [DisplayName("جمع شدن آینه های بقل")]
        public string SideMirrorSystem { get; set; }
        [DisplayName("توضیحات")]
        public string Details { get; set; }
        public Nullable<int> CarsId { get; set; }
    
        public virtual Car Car { get; set; }
    }
}
