//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarProject.DBSEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class NameOfValue
    {
        public int NameOfvaluesId { get; set; }
        public string AirConditioningType { get; set; }
        public string AirConditioningTypeDetails { get; set; }
        public string AirConditioningSystemDetailSubject { get; set; }
        public string AirConditioningSystemDetail { get; set; }
        public string FrontBrakeSystem { get; set; }
        public string RearBrakeSystem { get; set; }
        public string OtherSystem { get; set; }
        public string HandBrakeSystem { get; set; }
        public string BrakeDetails { get; set; }
        public Nullable<bool> DriverAirBag { get; set; }
        public Nullable<bool> FrontAirBag { get; set; }
        public Nullable<bool> AirBag { get; set; }
        public Nullable<int> AirBagEntity { get; set; }
        public string AirBagDetails { get; set; }
        public string AudioSystemType { get; set; }
        public string AudioSystemBrand { get; set; }
        public Nullable<bool> HasMonitor { get; set; }
        public Nullable<bool> RearSeatsMonitor { get; set; }
        public Nullable<bool> RearGearCamera { get; set; }
        public Nullable<bool> FrontCamera { get; set; }
        public string RearStereo { get; set; }
        public string FrontStereo { get; set; }
        public string Subwoofer { get; set; }
        public string Amplifire { get; set; }
        public Nullable<bool> HasGps { get; set; }
        public string CarAudioSystemDetails { get; set; }
        public string CarBrandName { get; set; }
        public string CarBrandHistory { get; set; }
        public Nullable<int> OilChangeDate { get; set; }
        public Nullable<int> OilChangeMilage { get; set; }
        public Nullable<int> OilFiltersChangeDate { get; set; }
        public Nullable<int> OilFilterChangeMilage { get; set; }
        public Nullable<int> GearBoxOilChangeDate { get; set; }
        public Nullable<int> GearBoxOilChangeMilage { get; set; }
        public Nullable<int> AirFilterChangeDate { get; set; }
        public Nullable<int> AirFilterChangeMilage { get; set; }
        public Nullable<int> TiresChangeDate { get; set; }
        public Nullable<int> TiresChangeMilage { get; set; }
        public Nullable<int> TimingbeltChangeDate { get; set; }
        public Nullable<int> TimingbeltChangeMilage { get; set; }
        public Nullable<int> OtherBeltsChangeDate { get; set; }
        public Nullable<int> OtherBeltsChangeMilage { get; set; }
        public Nullable<int> FrontBrakePadsChangeDate { get; set; }
        public Nullable<int> FrontBrakePadsChangeMilage { get; set; }
        public Nullable<int> RearBreakePadsChangeDate { get; set; }
        public Nullable<int> RearBrakePadsChangeMilage { get; set; }
        public string EngineType { get; set; }
        public Nullable<int> EngineCylinderNumber { get; set; }
        public Nullable<int> EnginePowerHpRpm { get; set; }
        public Nullable<int> EngineTorque { get; set; }
        public Nullable<int> EnginePowerHpTon { get; set; }
        public Nullable<int> EnginePowerHpLitr { get; set; }
        public Nullable<int> EngineMaxSpeed { get; set; }
        public Nullable<double> EngineZeroToH { get; set; }
        public string EngineDescription { get; set; }
        public Nullable<int> EngineSize { get; set; }
        public string EngineFuel { get; set; }
        public string GearBoxCode { get; set; }
        public string GearBoxType { get; set; }
        public Nullable<bool> GearBoxCanBeManual { get; set; }
        public Nullable<int> GearBoxShiftNumber { get; set; }
        public string GearBoxAxel { get; set; }
        public Nullable<bool> HasTransferCase { get; set; }
        public Nullable<bool> GearBoxDiffrentionalLock { get; set; }
        public string GearBoxWdType { get; set; }
        public string GearBoxDescription { get; set; }
        public Nullable<bool> GearBoxShifter { get; set; }
        public string FrontLights { get; set; }
        public string RearLights { get; set; }
        public Nullable<bool> DayLight { get; set; }
        public Nullable<bool> SideMirrorLight { get; set; }
        public Nullable<bool> FonrAntiFog { get; set; }
        public Nullable<bool> RearAntiFog { get; set; }
        public Nullable<bool> ReadingLamp { get; set; }
        public string LightsDeailts { get; set; }
        public Nullable<bool> ThirdLightStop { get; set; }
        public string CarModelName { get; set; }
        public Nullable<int> CarLength { get; set; }
        public Nullable<int> Carwidth { get; set; }
        public Nullable<int> CarHeight { get; set; }
        public Nullable<int> CarTrack { get; set; }
        public Nullable<int> CarWheelBase { get; set; }
        public Nullable<int> CarPureWeight { get; set; }
        public Nullable<int> CarTankSize { get; set; }
        public string CarPhysicalDetails { get; set; }
        public Nullable<double> Price { get; set; }
        public string CarsClass { get; set; }
        public Nullable<double> CarsUserScore { get; set; }
        public Nullable<double> CarsClinicScore { get; set; }
        public string CarsVideoURL { get; set; }
        public string CarsDescription { get; set; }
        public string CarClassType { get; set; }
        public string CarCategory { get; set; }
        public string CarUsage { get; set; }
        public Nullable<int> CarYearModel { get; set; }
        public string CarBodyType { get; set; }
        public Nullable<bool> LongitudinalDisplacement { get; set; }
        public Nullable<bool> BezelSet { get; set; }
        public Nullable<bool> SeatWarmer { get; set; }
        public Nullable<bool> SeatMassage { get; set; }
        public Nullable<bool> HasMemory { get; set; }
        public string CarSeatDetails { get; set; }
        public Nullable<bool> DayLightSensor { get; set; }
        public Nullable<bool> RainSensor { get; set; }
        public Nullable<bool> RearGearSensor { get; set; }
        public Nullable<bool> ParkSensor { get; set; }
        public Nullable<bool> NavigateSensor { get; set; }
        public Nullable<bool> CruiseControl { get; set; }
        public string SensorDetails { get; set; }
        public Nullable<bool> CarsProOrCro { get; set; }
        public string CarProCro { get; set; }
        public string QuestionType { get; set; }
        public string Question { get; set; }
        public string Review { get; set; }
        public Nullable<double> CarScore { get; set; }
        public Nullable<double> Beauty { get; set; }
        public Nullable<double> WorthBuying { get; set; }
        public Nullable<double> Quality { get; set; }
        public Nullable<double> Services { get; set; }
        public string CarsReviewSubject { get; set; }
        public string CarsReview { get; set; }
        public string TireType { get; set; }
        public Nullable<int> RingStandardSize { get; set; }
        public string TireSpec { get; set; }
        public string RingType { get; set; }
        public string RingModel { get; set; }
        public Nullable<bool> AutoInflated { get; set; }
        public string CarTireDetails { get; set; }
        public string CountryShortName { get; set; }
        public string CountryLongName { get; set; }
        public string DetailedName { get; set; }
        public Nullable<bool> HaveDetailed { get; set; }
        public Nullable<double> LphCity { get; set; }
        public Nullable<double> LphRoad { get; set; }
        public Nullable<double> LphMix { get; set; }
        public string FuelDetails { get; set; }
        public string ReservedOne { get; set; }
        public string ReservedTwo { get; set; }
        public string ReservedThree { get; set; }
        public string FrontWindscreens { get; set; }
        public string RearWindscreens { get; set; }
        public Nullable<bool> SunRoof { get; set; }
        public Nullable<bool> PanaromaRoof { get; set; }
        public Nullable<bool> RearGlassWarmer { get; set; }
        public Nullable<bool> WindscreensWarmer { get; set; }
        public Nullable<bool> FrontGlassWarmer { get; set; }
        public string SideMirrorSet { get; set; }
        public string SideMirrorSystem { get; set; }
        public string MirrorsDetails { get; set; }
        public string ManufactureName { get; set; }
        public string Address { get; set; }
        public string ManufacturePhon { get; set; }
        public Nullable<bool> RemoteControl { get; set; }
        public Nullable<bool> BurglarAlarm { get; set; }
        public Nullable<bool> Alarm { get; set; }
        public Nullable<bool> Emo { get; set; }
        public Nullable<bool> KeylessDoor { get; set; }
        public Nullable<bool> KeylessStart { get; set; }
        public string SecurityDetails { get; set; }
        public string SteeringSystemType { get; set; }
        public string SteeringType { get; set; }
        public Nullable<bool> SteeringHeightAdjustble { get; set; }
        public Nullable<bool> SteeringControlKey { get; set; }
        public string SteeringDetails { get; set; }
    }
}
