//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarProject.DBSEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonCar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PersonCar()
        {
            this.PersonCarDetails = new HashSet<PersonCarDetail>();
        }
    
        public int PersonCarsId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> CarId { get; set; }
        public Nullable<int> CarMilage { get; set; }
        public string CarCreationDate { get; set; }
        public string CarColor { get; set; }
        public string CarPlate { get; set; }
        public Nullable<int> CarPlateCityCode { get; set; }
    
        public virtual Car Car { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonCarDetail> PersonCarDetails { get; set; }
        public virtual User User { get; set; }
    }
}
