//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarProject.DBSEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonCarDetail
    {
        public int PersonCarDetailId { get; set; }
        public Nullable<int> PersonCarId { get; set; }
        public Nullable<System.DateTime> LastOilChange { get; set; }
        public Nullable<System.DateTime> LastFiltersChange { get; set; }
        public Nullable<int> LastOilChangeMilage { get; set; }
        public Nullable<int> LastFilterChangeMilage { get; set; }
    
        public virtual PersonCar PersonCar { get; set; }
    }
}
