//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarProject.DBSEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonProductEntity
    {
        public int PersonProductEntityId { get; set; }
        public Nullable<int> PersonProductId { get; set; }
        public Nullable<System.DateTime> DateUsed { get; set; }
        public Nullable<int> EntityUsed { get; set; }
    
        public virtual PersonProduct PersonProduct { get; set; }
    }
}
