//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarProject.DBSEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonProduct
    {
        public int PersonProductId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<bool> UsedProduct { get; set; }
        public Nullable<int> AutoServiceId { get; set; }
        public Nullable<bool> UsedService { get; set; }
        public Nullable<int> AutoServicePackId { get; set; }
        public Nullable<bool> UsedPack { get; set; }
    
        public virtual AutoService AutoService { get; set; }
        public virtual AutoServicePack AutoServicePack { get; set; }
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
