//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarProject.DBSEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductQnA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductQnA()
        {
            this.Products = new HashSet<Product>();
            this.ProductQnA1 = new HashSet<ProductQnA>();
        }
    
        public int ProductQnAId { get; set; }
        public string ProductQuestion { get; set; }
        public Nullable<bool> HasAnswer { get; set; }
        public Nullable<bool> HasFather { get; set; }
        public Nullable<int> FatherId { get; set; }
        public string Answer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductQnA> ProductQnA1 { get; set; }
        public virtual ProductQnA ProductQnA2 { get; set; }
    }
}
