//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarProject.DBSEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductInService
    {
        public int ProductInServiceId { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public Nullable<int> ProductId { get; set; }
    
        public virtual AutoService AutoService { get; set; }
        public virtual Product Product { get; set; }
    }
}
