
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CarProject.DBSEF
{

using System;
    using System.Collections.Generic;
    
public partial class ProductPrice
{

    public int ProductPriceId { get; set; }

    public Nullable<int> ProductId { get; set; }

    public Nullable<int> ProductPrice1 { get; set; }

    public Nullable<System.DateTime> Date { get; set; }



    public virtual Product Product { get; set; }

}

}
