//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace CarProject.DBSEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecuritySystem
    {
        public int SecuritySystemsId { get; set; }
        [DisplayName("ریموت کنترل")]
        public Nullable<bool> RemoteControl { get; set; }
        [DisplayName("دزدگیر")]
        public Nullable<bool> BurglarAlarm { get; set; }
        [DisplayName("آژیر")]
        public Nullable<bool> Alarm { get; set; }
        [DisplayName("ایموبلایزر")]
        public Nullable<bool> Emo { get; set; }
        [DisplayName("باز شدن خودرو بدون کلید")]
        public Nullable<bool> KeylessDoor { get; set; }
        [DisplayName("استارت خودرو بدون کلید")]
        public Nullable<bool> KeylessStart { get; set; }
        [DisplayName("توضیحات")]
        public string Details { get; set; }
        public Nullable<int> CarId { get; set; }
    
        public virtual Car Car { get; set; }
    }
}
