//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarProject.DBSEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecuritySystem
    {
        public int SecuritySystemsId { get; set; }
        public Nullable<bool> RemoteControl { get; set; }
        public Nullable<bool> BurglarAlarm { get; set; }
        public Nullable<bool> Alarm { get; set; }
        public Nullable<bool> Emo { get; set; }
        public Nullable<bool> KeylessDoor { get; set; }
        public Nullable<bool> KeylessStart { get; set; }
        public string Details { get; set; }
        public Nullable<int> CarId { get; set; }
    
        public virtual Car Car { get; set; }
    }
}
