//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace CarProject.DBSEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SteeringSystem
    {
        public int SteeringSystemId { get; set; }
        [DisplayName("نوع سیستم فرمان")]
        public string SteeringSystemType { get; set; }
        [DisplayName("مدل فرمان")]
        public string SteeringType { get; set; }
        [DisplayName("امکان تنظیم ارتفاع فرمان")]
        public Nullable<bool> SteeringHeightAdjustble { get; set; }
        [DisplayName("دکمه های کنترلی روی فرمان")]
        public Nullable<bool> SteeringControlKey { get; set; }
        [DisplayName("توضیحات")]
        public string Details { get; set; }
        public Nullable<int> CarId { get; set; }
    
        public virtual Car Car { get; set; }
    }
}
