//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarProject.DBSEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeOfDay
    {
        public int TimeOfDayId { get; set; }
        public string TimePeriod { get; set; }
        public Nullable<int> DaysOfWeekId { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual DaysOfWeek DaysOfWeek { get; set; }
    }
}
