//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarProject.DBSEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToBasket
    {
        public int ToBasketId { get; set; }
        public Nullable<int> BasketId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> ProductEntity { get; set; }
        public Nullable<int> AutoServiceId { get; set; }
        public Nullable<int> AutoServiceEntity { get; set; }
        public Nullable<int> AutoServicePackId { get; set; }
        public Nullable<int> AutoSericePackEntity { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual AutoService AutoService { get; set; }
        public virtual AutoServicePack AutoServicePack { get; set; }
        public virtual Basket Basket { get; set; }
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
